/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { Button } from "laya/ui/Button";
import { Sprite } from "laya/display/Sprite";
export module ui {
	export class StartUI extends Scene {
		public referenceClass:Array<any>=[Button, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
}
export module ui.test {
	export class BackTracingSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class ConsoleUnitUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class DictionarySceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class DynamicProgramingSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class FunctionalTestUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class GraphSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class GreedySceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class HashTableSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class HeapSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class LinkedListSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class QueueSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class RecursiveSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class SearchSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class SetSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class SortingSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class StackSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
	export class TreeSceneUI extends Scene {
		public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
}