/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Start from "./script/Start"
import BackTracingTest from "./script/BackTracingTest"
import Go2StartScene from "./script/Go2StartScene"
import UnitConsole from "./script/UnitConsole"
import DictionaryTest from "./script/DictionaryTest"
import DynamicProgramingTest from "./script/DynamicProgramingTest"
import FunctionalTest from "./script/FunctionalTest"
import GraphTest from "./script/GraphTest"
import GreedyTest from "./script/GreedyTest"
import HashTableTest from "./script/HashTableTest"
import HeapTest from "./script/HeapTest"
import LinkedListTest from "./script/LinkedListTest"
import QueueTest from "./script/QueueTest"
import RecursiveTest from "./script/RecursiveTest"
import SearchTest from "./script/SearchTest"
import SetTest from "./script/SetTest"
import SortingTest from "./script/SortingTest"
import StackTest from "./script/StackTest"
import TreeTest from "./script/TreeTest"
import { ClassUtils } from "laya/utils/ClassUtils";
import { ui } from "./ui/layaMaxUI";
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Start.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = ClassUtils.regClass;
		reg("ui", ui);
        reg("script/Start.ts",Start);
        reg("script/BackTracingTest.ts",BackTracingTest);
        reg("script/Go2StartScene.ts",Go2StartScene);
        reg("script/UnitConsole.ts",UnitConsole);
        reg("script/DictionaryTest.ts",DictionaryTest);
        reg("script/DynamicProgramingTest.ts",DynamicProgramingTest);
        reg("script/FunctionalTest.ts",FunctionalTest);
        reg("script/GraphTest.ts",GraphTest);
        reg("script/GreedyTest.ts",GreedyTest);
        reg("script/HashTableTest.ts",HashTableTest);
        reg("script/HeapTest.ts",HeapTest);
        reg("script/LinkedListTest.ts",LinkedListTest);
        reg("script/QueueTest.ts",QueueTest);
        reg("script/RecursiveTest.ts",RecursiveTest);
        reg("script/SearchTest.ts",SearchTest);
        reg("script/SetTest.ts",SetTest);
        reg("script/SortingTest.ts",SortingTest);
        reg("script/StackTest.ts",StackTest);
        reg("script/TreeTest.ts",TreeTest);
    }
}
GameConfig.init();